/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: SkateWizrd.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @SkateWizrd: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("questions", () => this.@questions, val => this.@questions = val);
		}

		public StoryVar @questions;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@SkateWizrd()
	{
		this.StartPassage = "Intro";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
		passage20_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Intro

	void passage1_Init()
	{
		this.Passages[@"Intro"] = new StoryPassage(@"Intro", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("You walk past an unfamiliar store, is it new? You've lived here your whole life and not once seen this place. A giant neon sign illuminates the street, it reads \"Wiz-Kid Skate\". It seems to be a skate shop, a magic shop, some wierd hybrid? The store beckons you, almost as if you feel the store itself call your name. Going against your better judgment you decide to go in, I mean at least it looks cool? ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Enter Store", "Enter Store", null);
		yield break;
	}


	// .............
	// #2: Enter Store

	void passage2_Init()
	{
		this.Passages[@"Enter Store"] = new StoryPassage(@"Enter Store", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("A little bell rings as you pass through the door and you begin to take in the store's atmosphere. The deep purple walls are littered with skateboard racks and banners with illegible sigils. The store is full of clothing racks of skate apparel and cloaks and display cases with skateboard parts and crystals. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("You notice a weird looking man wearing a cheap wizard costume standing behind the counter. He greats you with a wave");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Talk to Clerk", "Talk to Clerk", null);
		yield break;
	}


	// .............
	// #3: Talk to Clerk

	void passage3_Init()
	{
		this.Passages[@"Talk to Clerk"] = new StoryPassage(@"Talk to Clerk", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Wizard: Greetings mortal and welcome to Wiz-Kid skate emporium where the line between the mysicial and the radical merges. Can I interest you in our wares?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("What is this place?", "What is this place?", null);
		yield return lineBreak();
		yield return link("When did you open?", "When did you open?", null);
		yield return lineBreak();
		yield return link("Magic?", "Magic?", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Well got anything cool?", "Well got anything cool?", null);
		yield break;
	}


	// .............
	// #4: What is this place?

	void passage4_Init()
	{
		this.Passages[@"What is this place?"] = new StoryPassage(@"What is this place?", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		Vars.questions  = Vars.questions + 1;
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Wizard: Did you not hear my greeting, I said \"Greetings mortal and welcome to Wiz-Kid skate emporium where the line between the mysicial and the radical merges. Can I interest you in our wares?\" ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Talk to Clerk", "Talk to Clerk", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #5: When did you open?

	void passage5_Init()
	{
		this.Passages[@"When did you open?"] = new StoryPassage(@"When did you open?", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		Vars.questions  = Vars.questions + 1;
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Wizard: We've been here for a long long time, we've been here before this towns founding. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Then why have I never seen this store?", "Then why have I never seen this store?", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #6: Magic?

	void passage6_Init()
	{
		this.Passages[@"Magic?"] = new StoryPassage(@"Magic?", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		Vars.questions  = Vars.questions + 1;
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Wizard: Yes, Magic.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Just as the Wizard finishes his sentence he brings out a cheap wand and with a flick fake flowes spring out. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Talk to Clerk", "Talk to Clerk", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #7: Then why have I never seen this store?

	void passage7_Init()
	{
		this.Passages[@"Then why have I never seen this store?"] = new StoryPassage(@"Then why have I never seen this store?", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("Wizard: That just means you haven't been looking.");
		yield return lineBreak();
		yield return text(".");
		yield return lineBreak();
		yield return text(".");
		yield return lineBreak();
		yield return text(".");
		yield return lineBreak();
		yield return text("Wizard: Also really? You missed the bright neon sign outside?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Talk to Clerk", "Talk to Clerk", null);
		yield return text(" ");
		yield break;
	}


	// .............
	// #8: Well got anything cool?

	void passage8_Init()
	{
		this.Passages[@"Well got anything cool?"] = new StoryPassage(@"Well got anything cool?", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("Wizard: Why yes we have many \"cool\" things but you're going to have to be specific. We have crystals embeded with the souls of demons, cloaks made out of unicorn hair, hoodies for 15% off. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Got anything that can help me make friends?", "Got anything that can help me make friends?", null);
		yield break;
	}


	// .............
	// #9: Got anything that can help me make friends?

	void passage9_Init()
	{
		this.Passages[@"Got anything that can help me make friends?"] = new StoryPassage(@"Got anything that can help me make friends?", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("Wizard: If friendship is what you seek that kind of powerful magic is out of your reach. Friendship magic is very dangerous and not something to be toyed with. However, I do have this.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("The Wizard pulls out a skateboard with a bright teal lighting bolt and crystal wheels.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Wizard: With this bad boi you'll make friends in no time. Will you accept the responsability of the board?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Wow can I try it out?", "Wow can I try it out?", null);
		yield break;
	}


	// .............
	// #10: Wow can I try it out?

	void passage10_Init()
	{
		this.Passages[@"Wow can I try it out?"] = new StoryPassage(@"Wow can I try it out?", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("Wizard: Uh not so fast, you can't just try out the skateboards. You have to buy it before you can ride it you fool.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Fine how much is it?", "Fine how much is it?", null);
		yield break;
	}


	// .............
	// #11: Fine how much is it?

	void passage11_Init()
	{
		this.Passages[@"Fine how much is it?"] = new StoryPassage(@"Fine how much is it?", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("Wizard: The price can be negotiated later, what I'm asking is do you want the skateboard, yes or no?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("What do you mean the price can be negotiated later?", "What do you mean the price can be negotiated later?", null);
		yield break;
	}


	// .............
	// #12: What do you mean the price can be negotiated later?

	void passage12_Init()
	{
		this.Passages[@"What do you mean the price can be negotiated later?"] = new StoryPassage(@"What do you mean the price can be negotiated later?", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("Wizard: Thats not important right now, whats important is that you use this board to make friends so you don't dissapoint your dear friend turtle when no one shows up to your party.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Wait how did you know that?!", "Wait how did you know that?!", null);
		yield break;
	}


	// .............
	// #13: Wait how did you know that?!

	void passage13_Init()
	{
		this.Passages[@"Wait how did you know that?!"] = new StoryPassage(@"Wait how did you know that?!", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("Wizard: I'm a wizard, and all powerful and knowing being, and I know you want this skateboard. Now I'll ask again will you accept the responsability of this board? ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Yes...", "Yes...", null);
		yield break;
	}


	// .............
	// #14: Yes...

	void passage14_Init()
	{
		this.Passages[@"Yes..."] = new StoryPassage(@"Yes...", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("Wizard: Cool welp here you go");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("The wizard hands you the board and you feel an exhilirating power surge through your body, as if you have been struck by the teal lighting depicted on the board. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Hop on the board", "Hop on the board", null);
		yield break;
	}


	// .............
	// #15: Hop on the board

	void passage15_Init()
	{
		this.Passages[@"Hop on the board"] = new StoryPassage(@"Hop on the board", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("Right as you hop on the board the lights in the store begin to flicker on and off rapidly and you see flashes of lightning outside. The lights begin acting norally and what ever storm was outside has subdued. You begin to skate back and forth. It seems like a normal skateboard. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("So now what?", "So now what?", null);
		yield break;
	}


	// .............
	// #16: So now what?

	void passage16_Init()
	{
		this.Passages[@"So now what?"] = new StoryPassage(@"So now what?", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("Wizard: Now you cast magic through the skateboard, but it will cost you.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("What do you mean?", "What do you mean?", null);
		yield break;
	}


	// .............
	// #17: What do you mean?

	void passage17_Init()
	{
		this.Passages[@"What do you mean?"] = new StoryPassage(@"What do you mean?", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		yield return text("Wizard: Try stepping off the board.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Attempt to get of the skateboard", "Attempt to get of the skateboard", null);
		yield break;
	}


	// .............
	// #18: Attempt to get of the skateboard

	void passage18_Init()
	{
		this.Passages[@"Attempt to get of the skateboard"] = new StoryPassage(@"Attempt to get of the skateboard", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		yield return text("As you attempt to hop off you feel as though your feet have fused to the skateboard. You try and hop only to perform an ollie. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Hey what the heck?!", "Hey what the heck?!", null);
		yield break;
	}


	// .............
	// #19: Hey what the heck?!

	void passage19_Init()
	{
		this.Passages[@"Hey what the heck?!"] = new StoryPassage(@"Hey what the heck?!", new string[]{  }, passage19_Main);
	}

	IStoryThread passage19_Main()
	{
		yield return text("Wizard: I did say there would be a price, you've been cursed to ride the skateboard until the day you die. You didn't think magic came for free.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("You never told me that part!", "You never told me that part!", null);
		yield break;
	}


	// .............
	// #20: You never told me that part!

	void passage20_Init()
	{
		this.Passages[@"You never told me that part!"] = new StoryPassage(@"You never told me that part!", new string[]{  }, passage20_Main);
	}

	IStoryThread passage20_Main()
	{
		yield return text("Wizard: Sucks kid, have a good life HAHAHAHA!");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Suddenly the Wizard drops a smokebomb and leaves the store. You notice he skateboards rather instead of running. And just like that you're alone in the store, unable to get off the board and unsure of how to do any of this \"magic\" you were promised. You go to the only logical location next, the skate park to see if anyone can help you learn some sick tricks. ");
		yield break;
	}


}